name: idle_detector_wrapper
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/robrob-creator/idle_detector_wrapper

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  test: any
