name: idle_detector_wrapper
description: A comprehensive Flutter package for idle detection with full web scroll support, mouse movement, keyboard input, and touch gesture detection.
version: 1.2.1
repository: https://github.com/robrob-creator/idle_detector_wrapper

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: any
  test: any
